build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t web2py-anuncios .
    - docker run -d --rm --name anuncios web2py-anuncios
    - docker stop anuncios