build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t artem-application .
    - docker network create my-network
    - docker run -d --rm --name my-postgres --network my-network -p 5432:5432 -v anuncios-postgres-data:/var/lib/postgresql/data -e POSTGRES_PASSWORD=postgres -d postgres
    - docker run -d --rm --name artem-application --network my-network artem-application
    - docker ps -a
    - wget http://0.0.0.0:8000
  