postgress-start-job:
  services:
  - postgres:12.2-alpine
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - psql --host=localhost --port=5432 --username=$POSTGRES_USER postgres < "CREATE DATABASE test_database ENCODING 'UTF8' LC_COLLATE 'es_ES.UTF-8' LC_CTYPE 'es_ES.UTF-8' TEMPLATE template0;"
